export const SET_USERS           = 'SET_USERS'
export const SET_USERS_REQUEST   = 'SET_USERS_REQUEST'
export const SET_STORIES         = 'SET_STORIES'
export const SET_STORIES_REQUEST = 'SET_STORIES_REQUEST'
export const SET_CURRENT_USER    = 'SER_CURRENT_USER'